# FIle name: main.py
# external library: requirements.sh
# OS: ubuntu-latest

name: Python Package using Conda

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      matrix:
        python-version: ['3.x']
    name: Python ${{ matrix.python-version }} sample
    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - run: cd Assignment\ 1; chmod 777 main.sh; ./main.sh
